//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod campaign;
pub mod class;
pub mod product;
pub mod product_campaign;
pub mod product_campaign_sale;
pub mod sale;
pub mod user;
