//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::campaign::Entity as Campaign;
pub use super::class::Entity as Class;
pub use super::product::Entity as Product;
pub use super::product_campaign::Entity as ProductCampaign;
pub use super::product_campaign_sale::Entity as ProductCampaignSale;
pub use super::sale::Entity as Sale;
pub use super::user::Entity as User;
